# https://pre-commit.com/#creating-new-hooks
- id: prepare-commit-msg
  name: "PartCAD: Prepare Commit Message"
  description: A hook to assist with git commit messages using AI.
  entry: prepare-commit-msg.py
  language: script
  args: ["--commit-msg-filename"]
  stages: [prepare-commit-msg]
  pass_filenames: true
- id: keep-a-changelog
  name: "PartCAD: Update CHANGELOG.md"
  description: A hook to assist with updating CHANGELOG.md using AI.
  entry: keep-a-changelog.py
  language: script
  fail_fast: true
  stages: [pre-commit]
  pass_filenames: false
